name: 'GitHub Actions Bot'

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  bot:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v1

    - name: crontab
      run: |
        curl https://mina.baobeihuijia.com/?aaaa
      env:
        CI: true
